import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { toast } from '../components/NotificationToast';
import { 
  Sparkles, Send, Bot, User, Compass, HelpCircle, Activity, 
  ShieldAlert, TrendingUp, AlertTriangle 
} from 'lucide-react';

export default function AiInsights() {
  // Chat state
  const [chatMessage, setChatMessage] = useState('');
  const [chatHistory, setChatHistory] = useState([
    { role: 'model', content: "Hello! I am HeroBot, your AI Community Coordinator. You can ask me how to organize volunteer projects, check checklists, earn reputation points (+10 join, +40 complete, +60 lead), or verify completions. How can I help you today?" }
  ]);
  const [sendingChat, setSendingChat] = useState(false);

  // Predictive insights state
  const [insights, setInsights] = useState(null);
  const [loadingInsights, setLoadingInsights] = useState(true);

  const fetchInsights = async () => {
    try {
      setLoadingInsights(true);
      const data = await api.getPredictiveInsights();
      setInsights(data);
    } catch (e) {
      console.error(e);
      toast.error("Failed to load predictive analytics.");
    } finally {
      setLoadingInsights(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  const handleSendChat = async (e, customMsg = null) => {
    if (e) e.preventDefault();
    const msgToSend = customMsg || chatMessage;
    if (!msgToSend.trim()) return;

    // Add user message to history
    const newHistory = [...chatHistory, { role: 'user', content: msgToSend }];
    setChatHistory(newHistory);
    setChatMessage('');
    setSendingChat(true);

    try {
      // Backend expects history without the latest message as we pass it separately,
      // but to be safe we pass history and message
      const res = await api.sendChatMessage(msgToSend, chatHistory);
      setChatHistory([...newHistory, { role: 'model', content: res.reply }]);
    } catch (err) {
      toast.error("Assistant chat error. Check server status.");
    } finally {
      setSendingChat(false);
    }
  };

  const getUrgencyColor = (prob) => {
    const val = parseInt(prob);
    if (val >= 80) return 'text-red-600 bg-red-100 dark:bg-red-950/40 dark:text-red-400';
    if (val >= 50) return 'text-amber-600 bg-amber-100 dark:bg-amber-950/40 dark:text-amber-400';
    return 'text-green-600 bg-green-100 dark:bg-green-950/40 dark:text-green-400';
  };

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      
      {/* HEADER SECTION */}
      <div className="mb-8 flex items-center justify-between border-b pb-6">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white flex items-center">
            <Sparkles className="mr-2 text-indigo-500 animate-pulse" />
            AI Civic Hub & Predictive Insights
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Interact with our AI Civic Assistant or explore historical patterns and predictive warnings generated by Gemini.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
        
        {/* LEFT THREE COLUMNS: AI CIVIC ASSISTANT CHATBOT */}
        <div className="lg:col-span-3 flex flex-col h-[600px] border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 rounded-3xl overflow-hidden shadow-sm">
          
          {/* Assistant Header */}
          <div className="p-4 border-b border-slate-100 bg-slate-50 dark:border-slate-850 dark:bg-slate-950 flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 rounded-xl bg-indigo-100 text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-400 flex items-center justify-center font-bold">🤖</div>
              <div>
                <h4 className="font-bold text-xs text-slate-950 dark:text-white">HeroBot</h4>
                <p className="text-[9px] text-emerald-500 font-semibold flex items-center">● AI Assistant Online</p>
              </div>
            </div>
            
            <button 
              onClick={() => setChatHistory([chatHistory[0]])}
              className="text-[10px] text-slate-400 hover:text-slate-600 font-semibold hover:underline"
            >
              Reset Chat
            </button>
          </div>

          {/* Chat Messages Log */}
          <div className="flex-1 p-4 overflow-y-auto space-y-4">
            {chatHistory.map((chat, idx) => (
              <div 
                key={idx}
                className={`flex items-start space-x-3 text-xs max-w-xl ${chat.role === 'user' ? 'ml-auto flex-row-reverse space-x-reverse' : 'mr-auto'}`}
              >
                <div className={`p-2 rounded-xl border flex items-center justify-center font-bold text-base ${chat.role === 'user' ? 'bg-primary-100 border-primary-200 text-primary-600 dark:bg-primary-950/30' : 'bg-slate-100 border-slate-200 text-slate-600 dark:bg-slate-950 dark:border-slate-800'}`}>
                  {chat.role === 'user' ? <User size={14} /> : <Bot size={14} />}
                </div>

                <div className={`p-3 rounded-2xl border leading-relaxed ${chat.role === 'user' ? 'bg-primary-600 border-primary-700 text-white' : 'bg-slate-50 border-slate-100 dark:bg-slate-950 dark:border-slate-850 dark:text-slate-300'}`}>
                  {chat.content}
                </div>
              </div>
            ))}
            
            {sendingChat && (
              <div className="flex items-center space-x-2 text-slate-400 text-xs pl-12 animate-pulse">
                <span>🤖 Bot is typing...</span>
              </div>
            )}
          </div>

          {/* Quick-Prompt Suggestions bar */}
          <div className="p-3 bg-slate-50/50 border-t border-slate-100 dark:border-slate-850 dark:bg-slate-950/40 flex flex-wrap gap-2">
            <button 
              onClick={() => handleSendChat(null, "How do I earn reputation points?")}
              className="px-3 py-1.5 rounded-full border border-slate-200 hover:bg-slate-100 dark:border-slate-800 dark:hover:bg-slate-900 text-[10px] text-slate-500 font-semibold"
            >
              How do points work?
            </button>
            <button 
              onClick={() => handleSendChat(null, "What is the timeline of reported issues?")}
              className="px-3 py-1.5 rounded-full border border-slate-200 hover:bg-slate-100 dark:border-slate-800 dark:hover:bg-slate-900 text-[10px] text-slate-500 font-semibold"
            >
              Explain status stages
            </button>
            <button 
              onClick={() => handleSendChat(null, "How do I report a pothole?")}
              className="px-3 py-1.5 rounded-full border border-slate-200 hover:bg-slate-100 dark:border-slate-800 dark:hover:bg-slate-900 text-[10px] text-slate-500 font-semibold"
            >
              How do I report an issue?
            </button>
          </div>

          {/* Chat Form */}
          <form onSubmit={handleSendChat} className="p-4 border-t dark:border-slate-800 bg-white dark:bg-slate-900 flex space-x-2">
            <input 
              type="text" 
              value={chatMessage}
              onChange={(e) => setChatMessage(e.target.value)}
              placeholder="Ask HeroBot a civic or platform question..."
              className="flex-1 rounded-xl border border-slate-205 bg-slate-50 dark:border-slate-800 dark:bg-slate-950 px-4 py-3 text-xs focus:outline-none focus:border-primary-500"
            />
            <button 
              type="submit"
              disabled={sendingChat || !chatMessage.trim()}
              className="rounded-xl bg-primary-600 hover:bg-primary-750 text-white px-5 py-3 flex items-center justify-center shadow hover:scale-105 active:scale-95 transition disabled:opacity-50"
            >
              <Send size={14} />
            </button>
          </form>

        </div>

        {/* RIGHT TWO COLUMNS: AI PREDICTIVE INSIGHTS */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* INFRASTRUCTURE HEALTH SCORE */}
          <div className="bg-white border rounded-3xl dark:bg-slate-900 dark:border-slate-800 p-6 shadow-sm flex items-center space-x-6">
            <div className="h-20 w-20 rounded-full border-4 border-indigo-500/20 flex items-center justify-center flex-shrink-0 relative">
              <span className="text-xl font-black text-indigo-600 dark:text-indigo-400">
                {insights ? (insights.communityImpactScore || insights.infrastructureScore) : 84}%
              </span>
              <div className="absolute inset-0 rounded-full border-4 border-indigo-500 border-t-transparent animate-spin" style={{ animationDuration: '8s' }}></div>
            </div>
            <div>
              <h4 className="text-sm font-bold text-slate-950 dark:text-white uppercase tracking-wider mb-1">Collaborative Community Impact</h4>
              <p className="text-xs text-slate-400 leading-normal">
                An aggregated score representing neighborhood volunteering activity, completed actions, and verified resolutions.
              </p>
            </div>
          </div>

          {/* HISTORICAL PATTERNS & FORECASTS */}
          <div className="bg-white border rounded-3xl dark:bg-slate-900 dark:border-slate-800 p-6 shadow-sm space-y-4">
            <h4 className="text-xs font-bold text-slate-450 uppercase tracking-wider mb-2 flex items-center">
              <Activity size={14} className="mr-2 text-indigo-500" />
              Gemini Community Action Summary
            </h4>

            {loadingInsights ? (
              <div className="space-y-2 animate-pulse">
                <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-full"></div>
                <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-5/6"></div>
                <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-2/3"></div>
              </div>
            ) : (
              <p className="text-xs text-slate-700 dark:text-slate-350 leading-relaxed font-medium bg-slate-50 dark:bg-slate-950 p-4 border rounded-2xl">
                {insights?.summary}
              </p>
            )}
          </div>

          {/* PREDICTIVE INSIGHT CARD LIST */}
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider pl-1">Predictive volunteer campaigns</h4>
            
            {loadingInsights ? (
              [1, 2].map(i => (
                <div key={i} className="bg-white border p-5 rounded-3xl animate-pulse space-y-3">
                  <div className="h-4 bg-slate-200 rounded w-1/3"></div>
                  <div className="h-3 bg-slate-200 rounded w-full"></div>
                  <div className="h-3 bg-slate-200 rounded w-1/2"></div>
                </div>
              ))
            ) : (
              insights?.predictions.map((pred, index) => (
                <div 
                  key={index}
                  className="bg-white border dark:bg-slate-900 dark:border-slate-800 rounded-3xl p-5 shadow-sm space-y-3"
                >
                  <div className="flex justify-between items-start">
                    <h5 className="font-extrabold text-sm text-slate-950 dark:text-white leading-snug">{pred.title}</h5>
                    <span className={`px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-wider ${getUrgencyColor(pred.probability)}`}>
                      Prob: {pred.probability}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-normal">{pred.description}</p>
                  
                  <div className="bg-slate-50 dark:bg-slate-950 border border-slate-100 dark:border-slate-850 p-3 rounded-2xl flex items-start space-x-2">
                    <AlertTriangle className="text-indigo-500 mt-0.5 flex-shrink-0" size={14} />
                    <div>
                      <p className="text-[9px] uppercase font-bold text-slate-400">Pre-emptive Recommendation</p>
                      <p className="text-[11px] text-slate-700 dark:text-slate-350 mt-1 leading-normal italic">
                        "{pred.recommendation}"
                      </p>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>

        </div>

      </div>

    </div>
  );
}
